apiVersion: apps/v1
kind: Deployment
metadata:
  name: noted-server
  labels:
    app: noted-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noted-server-deployment
  template:
    metadata:
      labels:
        app: noted-server-deployment
    spec:
      containers:
      - name: noted-server-c
        image: noted-server
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: noted-server-svc
spec:
  type: LoadBalancer
  selector:
    app: noted-server-deployment
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30001
