apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  labels:
    app: example-server-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-server-demo
  template:
    metadata:
      labels:
        app: example-server-demo
    spec:
      containers:
      - name: noted-server
        image: noted-server
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: example-server-src
spec:
  type: LoadBalancer
  selector:
    app: example-server-demo
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30001
